inspection_socket : inspection_socket.o 
	gcc -o inspection_socket  inspection_socket.o
    
inspection_socket.o : inspection_socket.c
	gcc -c -o inspection_socket.o inspection_socket.c

clean:
	rm -rf *.o inspection_socket
